### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by maverick-fox** [iagox86/hash_extender#29]
This error occurs after the launch in normal mode and after: ./hash_extender --test

**Comment by bl4zk0** [comment]
you can run it on docker

`docker run -it --platform linux/amd64 debian:bullseye`
then inside container:
```
cd && apt install -y make gcc libssl-dev git && \
git clone https://github.com/iagox86/hash_extender.git && \
cd hash_extender && make
```

**Comment by maverick-fox** [comment]
> you can run it on docker
> 
> `docker run -it --platform linux/amd64 debian:bullseye`
> 
> then inside container:
> 
> ```
> cd && apt update && apt install -y make gcc libssl-dev git && \
> git clone https://github.com/iagox86/hash_extender.git && \
> cd hash_extender && make
> ```

Hi!
Could you please explain why in a docker container it works but in the native Ubuntu terminal it doesn't ?
Thanks

**Comment by maverick-fox** [comment]
Thanks!

**Comment by iagox86** [comment]
thanks, I've been super bad at maintaining this! I started a re-write in Rust but life got in the way. It's using libs in a weird way, which is going to be annoying as versions get updated :(
