### ISSUE TITLE
Can't make hash_extender on Windows 7 x64

### ISSUE THREAD

**Issue by nirvana-msu** [iagox86/hash_extender#8]
Getting the following error:

```
$ make
[CC] formats.o
<command-line>: error: missing whitespace after the macro name
In file included from test.h:4,
                 from formats.c:4:
util.h:4:17: error: err.h: No such file or directory
make: *** [Makefile:39: formats.o] Error 1
```

Any pointers what should I do?

Thanks.

**Comment by iagox86** [comment]
I don't think it'll compile on Windows.. I didn't make any effort to make it compatible, so if anybody wants to try and get it to compile, you're welcome to try. :)
