### ISSUE TITLE
Can't "make" on Kali 2016.2

### ISSUE THREAD

**Issue by exploresecurity** [iagox86/hash_extender#9]
Hi
Compilation by "make" worked first time on old Kali, having issues with later Kali (2016.2). First I got:
_hash_extender_engine.c:25:25: fatal error: openssl/md4.h: No such file or directory_
I solved this by locating md4.h and added a -I/path/to/file in the CPPFLAGS of the Makefile. Next I got:
_/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto_
I found a ssl.so and crypto.so in different and pretty random-looking places. But I went ahead and added -L/path/to/file (twice to cover both files) in the LDFLAGS of the Makefile. But no joy.
Needless to say my make/gcc skills aren't great so help appreciated where Google is letting me down.
Cheers

**Comment by iagox86** [comment]
Try installing libssl-dev (I think that's what it's called). That might
help!

**Comment by exploresecurity** [comment]
Yup - that's it! That must have added the necessary header files and libraries in a much nicer and cleaner way than scrabbling around the file system!
Cheers

**Comment by iagox86** [comment]
Woohoo! I should probably add a readme file one day. :-)

**Comment by oliviajohansen** [comment]
This helped with compiling on mac! Thank you

**Comment by brawlerZX** [comment]
after installing libssl-dev I get the following error message for all the other hash,update and init functions
```
hash_extender_engine.c: In function ‘md4_hash’:
hash_extender_engine.c:362:3: error: ‘MD4_Init’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
```

**Comment by iagox86** [comment]
Hmm, that's annoying! We could turn off MD4 on certain systems, but maybe we can just disable that warning?

You might be able to fix that by removing `-Wno-deprecated` from the Makefile (as a workaround)
